### ISSUE TITLE
vanquish -hostFile host.txt

### ISSUE THREAD

**Issue by dover247** [frizb/Vanquish#2]
Traceback (most recent call last):
  File "/usr/local/bin/vanquish", line 4, in <module>
    Vanquish2.main()
  File "/usr/local/lib/python2.7/dist-packages/Vanquish2.py", line 879, in main
    vanquish = Vanquish(argv if argv else sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/Vanquish2.py", line 331, in __init__
    Logger.VERBOSE = (self.config.getboolean("System", "Verbose") or self.args.verbose)
  File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
    v = self.get(section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'System'

**Comment by frizb** [comment]
Thanks Dover247! 
It appears that Vanquish is unable to find the configuration files it requires.
config.ini
attackplan.ini

Looks like you have placed Vanquish in your /usr/local/lib/python2.7/dist-packages/Vanquish2.py

I would recommend you run vanquish in the same folder you git it to.
OR 
you can specify the path to the config and attack plan folders like so:


vanquish -hostFile test.txt -attackPlanFile 
/usr/local/lib/python2.7/dist-packages/attackplan.ini -configFile /usr/local/lib/python2.7/dist-packages/config.ini 

I will also work to improve the error message and perhaps change how Vanquish currently looks for its config and attackplan files.

**Comment by dover247** [comment]
Awesome! Thanks for your support!
